# This workflow defines a set of Terraform jobs for infrastructure management.

name: Terraform Workflow

on:
  push:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/actions/terraform@v1.3.0
        with:
          auto-approve: false

      - name: Initialize Terraform
        run: terraform init

  plan:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/actions/terraform@v1.3.0
        with:
          auto-approve: false

      - name: Preview Terraform plan
        run: terraform plan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/actions/terraform@v1.3.0
        with:
          auto-approve: false

      - name: Apply Terraform changes
        run: terraform apply
