name: 'terraform demo job'

on:
  push:
    branches: [ main ]

environment:
  name: 'dev'
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-setup:
    name: 'setting up system to run terraform code'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v2

      - name: 'installing terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'terraform version"
        run: terraform version




