name: Terraform

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      TERRAFORM_ACTION:
        description: 'Terraform deployments'
        required: true
        default: 'PLAN'
        type: choice
        options:
          - 'INIT'
          - 'PLAN'
          - 'APPLY'
          - 'DESTROY'

env:
  name: dev
  ACTIONS_STEP_DEBUG: true
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  terraform-check:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  terraform_init:
    name: terraform init
    runs-on: ubuntu-latest
    needs: ["terraform-check"]

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

  terraform_plan:
    name: terraform plan
    runs-on: ubuntu-latest
    needs: ["terraform_init"]
    if: ${{ github.event.inputs.TERRAFORM_ACTION == 'PLAN' || github.event.inputs.TERRAFORM_ACTION == 'APPLY' }}

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Terraform Init and plan
        run: terraform init && terraform plan

  terraform_apply:
    name: terraform apply
    runs-on: ubuntu-latest
    needs: ["terraform_plan"]
    if: ${{ github.event.inputs.TERRAFORM_ACTION == 'APPLY' }}

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Terraform Init and apply
        run: terraform init && terraform apply

  terraform_destroy:
    name: terraform destroy
    runs-on: ubuntu-latest
    needs: ["terraform-check"]
    if: ${{ github.event.inputs.TERRAFORM_ACTION == 'DESTROY' }}

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Terraform Init and destroy
        run: terraform init && terraform destroy --auto-approve
